apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://${ES_HOST}:${ES_PORT}
    jsonData:
      esVersion: "9.4.0"
      timeField: "@timestamp"
