apiVersion: 1

datasources:
  - name: GitHub API
    uid: P7DE29E761332DDA9
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: https://api.github.com
    jsonData:
      auth_method: bearerToken
    secureJsonData:
      bearerToken: ${GITHUB_TOKEN}

  - name: SonarCloud API
    uid: P15CC78D08580E45A
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: https://api.sonarcloud.io
    jsonData:
      auth_method: bearerToken
    secureJsonData:
      bearerToken: ${SONARCLOUD_TOKEN}

  - name: DefectDojo API
    uid: PBB192D6277AA7249
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: https://demo.defectdojo.org/api/v2
    jsonData:
      auth_method: apiKey
      apiKeyKey: Authorization
      apiKeyType: header
    secureJsonData:
      apiKeyValue: Token ${DEFECTDOJO_TOKEN}

  - name: Local JSON Server
    uid: PF9153EDC0117EC0B
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://json-server:3000
